INTEGER FACT
READ(5, *) X, N
SUMX= 0.0
J = 1
DO 7 I = 1, N, 2
SUMX = SUMX + FLOAT(J) * (X ** I / FLOAT(FACT(I)))
J = -J
7 CONTINUE
WRITE(6, 20) SUMX
20 FORMAT(2X, 'SIN X = ', F10.6) 
END
INTEGER FUNCTION FACT(K)
FACT = 1
DO 5 M = 1, K
FACT = FACT * M
5 CONTINUE
RETURN 
END
